### ISSUE TITLE
collect topics and concepts from related conferences

### ISSUE THREAD

**Issue by timm** [jsaat/jsaat.github.io#3]

**Comment by timm** [comment]
and those conferences are:

- icpc
- wcre, icsmr ==> saner
- msr
- icsme
- scam

![image](https://user-images.githubusercontent.com/29195/27240620-7f79aed8-52a3-11e7-9dde-74e201a58cb5.png)

**Comment by abramhindle** [comment]
https://github.com/jsaat/jsaat.github.io/blob/master/topics.md These are just CFP topics. Listed per conference. Need to be condensed.
