### ISSUE TITLE
manifesto needed

### ISSUE THREAD

**Issue by timm** [jsaat/jsaat.github.io#5]
gap in the literature

![image](https://user-images.githubusercontent.com/29195/27240683-bd4f3598-52a3-11e7-8845-472351b565d1.png)

experiment in next era of publication

**Comment by timm** [comment]
- who do we serve?

**Comment by timm** [comment]
not journal shares our emphasis.

**Comment by abramhindle** [comment]
Needs better explanation of diagram. And motivation of need.

# Isn't EMSE enough?

EMSE doesn't cover source code as much and MSR/ICSME has a different kind of empirical software engineering currently not reflected in EMSE.

**Comment by abramhindle** [comment]
# Accelerate research by principled preprinting and fast review

**Comment by abramhindle** [comment]
# Paper Bloat

**Comment by abramhindle** [comment]
# We shouldn't spend so much time writing papers
More time should be spent on the results than selling, gloating, and promoting the results.

**Comment by abramhindle** [comment]
# Choose a few of these and submit
https://github.com/researchart/all/blob/master/ListOfArtifacts.md
